### PR TITLE
Change match for excluded pages

### PR DESCRIPTION
**Pull request by ximeric**

### CODE REVIEW

**Comment by Drag13** [comment]
Hello @ximeric 

Very good finding with `i` flag, really!. But may I ask what are the purpose for other changes?

**Comment by ximeric** [comment]
Hello, @Drag13.

From commit comment: exclude news pages, fix post regex match, optimize check.
Code was minimized & simplified because all tests can be made by single expression in one place.

**Comment by Drag13** [comment]
Sounds great, but the point is that new regex is so complex, that I can't understand the fix from code :(

Would you be so kind to make a fix regex pre regex as this was before?

I would really appreciate your efforts and help

**Comment by ximeric** [comment]
Actually, this regex is not complex: full expression
/(users/.+/posts|company/.+/blog|post/\\d+|news/t/\\d+)/
can be split like this:

- '/' around the edges is literally '/' in the path;
- '(...)' is a group of expressions separated by '|' (match any expression in a group);
- each expression is: match for posts on user page ( users/.+/posts ), company post from blog ( company/.+/blog ), single user post ( post/\\d+ ), news post ( news/t/\\d+ );
- '.+' - is matched for any not null string (any char, match length > 1);
- '\\d+' is matched for number string ( digits, match length > 1).

I have a wide experience with regex'es, for example you can see proposed optimizations in a patch 
https://github.com/ldx/python-iptables/commit/d66e96ba4a4b7bcc0abdfa6cf0683b24dbb5843e, and  that regex is much more complex in comparison with this one)

**Comment by Drag13** [comment]
I understand that I am not the smartest person in the world, thanks :) But if the code is not readable for me, it might be not readable by others, that's why I am arguing for the splitting.

Another point is SRP - one thing at one time. Easier to read, easier to fix when Habr will change something in the path (hopefully not).

And if you are concerned about performance, you are right. 3 or even 4 regexes might be slower, than 1 but as far as it will be executed one time per page this is not a big price, at least from my point of view.

**Comment by ximeric** [comment]
Performance is not a goal.

There are many programmers in the world, who can write code which 90% other programmers will not understand. is this the reason that they should not write that code and help other projects? Or they must write code that all programmers with any skills will understand?

As I write before, full expression is nearly simple, and I explained how and why. For debugging can be used https://www.debuggex.com/.

This browser extension (and the place of patch correction) is not complex so SRP is an unnecessary complication in general: https://cutt.ly/TjYqrjz .

**Comment by Drag13** [comment]
Thanks for the explanation, I got your point.

I would gladly accept this PR when changes will be implemented for the splitted regexes

**Pull request closed without merging**
