### PR TITLE
UI: Action mini-buttons for interactive remove article for selected hub

### PR DESCRIPTION
**Pull request by ximeric**

### CODE REVIEW

**Comment by Drag13** [comment]
Hello @ximeric, thanks for the awesome new feature! I reviewed the code and really want to to add it to the extension.

However I would kindly ask you to do a few changes:

* Change ```a``` element to the ```button```. I am trying to follow the simplest WCAG rules and using non-semantic elements will lead to accessibility issues. 
* Add a new flag to the settings to turn on/off this feature with turned off by default. I don't think we should alter UI without the direct user's permission. 
* Fix the look of the icon. Right now it seems that it is not a circle. If this is intentional behavior, please let me know.

image

And thanks for all your efforts!

**Comment by ximeric** [comment]
Hello @Drag13, I'm glad that my work was appreciated!

Proposed changes were applied. Sadly, in the first commit 'button' was my late discarded desicion(

is it necessary to communicate in English in this repo/project (issues, PRs, etc)?

**Comment by Drag13** [comment]
Thanks for the update - looks much better now and I don't see any blocker points to hold this PR.

I still want to modify some stuff but as I mentioned before - it is not something super serious.

Regarding the language - I prefer to stick to English (to keep everything simple). But, of course, if it's not comfortable for you - I can switch to Ukrainian or Russian language - just let me know what suits you best.

**Comment by Drag13** [comment]
@ximeric 

I know that you spent a lot of time to make the hide button looks great, but what do you think if I change it to this one? 

image

**Comment by ximeric** [comment]
@Drag13, I think your variant looks much better)

**Pull request merged**
